### ISSUE TITLE
Design Explorations: Missing Blocks

### ISSUE THREAD

**Issue by melchoyce** [WordPress/block-library#12]
What happens if you’re missing a block, or import content with a block you don’t have installed?

Related: #8

**Comment by melchoyce** [comment]
If the block is present in the Block Directory:

![image](https://user-images.githubusercontent.com/2846578/61002918-a2681a80-a330-11e9-908e-a95a2caae818.png)

If it's not, we should probably leave as-is:

![image](https://user-images.githubusercontent.com/2846578/61002801-62a13300-a330-11e9-9b84-12371be03888.png)

**Comment by karmatosed** [comment]
Would creating a placeholder or style around this be nice? I am thinking of for example in Facebook when a page is loading the background color/style of those.  My thinking is otherwise it gets lost, this may be a fix to have in Gutenberg itself.

**Comment by melchoyce** [comment]
If someone's added custom styles to their block, the block itself might display just fine on the front-end. With a shortcode, you'll also want to know what shortcode you'd added to that page. Because of this, we should still show whatever content they're trying to load in the editor instead of replacing it with a placeholder, IMO.

**Comment by ck-lee** [comment]
The design looks good to me!

From dev's perspective, I think it should be OK to render the "unsupported block" in the editor. I will try and see, including any custom styles. Will let you know...

**Comment by melchoyce** [comment]
FWIW, Gutenberg currently does render the content of the unsupported block — that's where that shortcode screenshot comes from. For example, here's the Block Gallery plugin, _after_ being disabled:

![image](https://user-images.githubusercontent.com/2846578/61093246-88edce00-a417-11e9-8f0b-65f571668ece.png)

**Comment by karmatosed** [comment]
Can you confirm @melchoyce this is now completed?

**Comment by melchoyce** [comment]
Unless anyone has more feedback, then yes 👍
