### ISSUE TITLE
Consider adjusting or removing help panel

### ISSUE THREAD

**Issue by karmatosed** [WordPress/block-library#15]
Currently, on search, you see:

![image](https://user-images.githubusercontent.com/253067/63346501-0678f800-c34d-11e9-8096-5548acaccd07.png)

I wonder if this should be either closed or should be adjusted somehow when searching for blocks?

**Comment by melchoyce** [comment]
I think this is a question for the Gutenberg repo as a whole — the search behavior is native to Gutenberg, whether or not is shows results from the block directory.

**Comment by ck-lee** [comment]
![screencast 2019-08-21 11-02-56](https://user-images.githubusercontent.com/5370495/63390495-75b12380-c403-11e9-8e69-41c2fb9b331b.gif)

The current implementation will show more information of the (installed) block when mouse hover-over. I think we can take advantage of the new panel. But I'm not sure about doing it for v1. Keen to hear what you think.

**Comment by melchoyce** [comment]
How about something like this?

![inserter-panel](https://user-images.githubusercontent.com/2846578/63786037-5c0a5300-c8bf-11e9-845f-05e568b7fd53.png)

(Needs a copy review)

**Comment by ck-lee** [comment]
Looks good to me. 

However, the current implementation makes it difficult for `block-directory` to override/extend the help panel. 

I will try to get the main PR https://github.com/WordPress/gutenberg/pull/16524 merged. And then tackle this issue separately.

**Comment by StevenDufresne** [comment]
@melchoyce I am unable to find this view in Gutenberg @master. It appears like it was removed in favor of a floating block preview. If it no longer applies, can we close this out? :)

**Comment by melchoyce** [comment]
👍
