### ISSUE TITLE
Design explorations

### ISSUE THREAD

**Issue by karmatosed** [WordPress/block-library#2]
As work begins on this designs will be added to this issue to explore and get feedback.

- [x] Search #5 
- [x] Block Details #9
- [x] Previewing #6 
- [x] Installing #7 
- [x] Misc #8

**Comment by melchoyce** [comment]
Prior ideas:

![image](https://user-images.githubusercontent.com/2846578/58130416-f3d61200-7be9-11e9-964e-3f8cc5f11374.png)
![image](https://user-images.githubusercontent.com/2846578/58130421-f6d10280-7be9-11e9-9117-7aabe451a2aa.png)
![image](https://user-images.githubusercontent.com/2846578/58130453-06504b80-7bea-11e9-8221-6326b72f213b.png)
![image](https://user-images.githubusercontent.com/2846578/58130442-fc2e4d00-7be9-11e9-817e-56312bed4593.png)
![image](https://user-images.githubusercontent.com/2846578/58130429-f9cbf300-7be9-11e9-9445-220394aed6b9.png)
![image](https://user-images.githubusercontent.com/2846578/58130468-0ea88680-7bea-11e9-876e-8e3c12a712d9.png)
![image](https://user-images.githubusercontent.com/2846578/58130693-aefeab00-7bea-11e9-9684-3077958307d0.png)
![image](https://user-images.githubusercontent.com/2846578/58130474-11a37700-7bea-11e9-8fef-b24b545e45a4.png)
![image](https://user-images.githubusercontent.com/2846578/58130478-16682b00-7bea-11e9-82b9-d44c75e75406.png)

See: https://make.wordpress.org/design/2019/04/02/call-for-design-installing-blocks-from-within-gutenberg/
