### ISSUE TITLE
Experience flow diagram

### ISSUE THREAD

**Issue by karmatosed** [WordPress/block-library#3]
It would be great to work out all the flows and create a chart so that everyone is on the same page.

**Comment by melchoyce** [comment]
Here's what I'm thinking:

![image](https://user-images.githubusercontent.com/2846578/58132422-3c43fe80-7bef-11e9-9d03-41ccd6714728.png)
https://whimsical.com/98rHP1AShNHZq2nhBb8jyJ

Anything missing? Any states or situations I haven't accounted for?

**Comment by georgeolaru** [comment]
Nice flow @melchoyce! One note regarding the second step: considering that there might be multiple blocks accounting for the "slider" type (from different sources), would those be presented on search, even when there is a "slider" block already installed?

**Comment by melchoyce** [comment]
I think we could consider adding a callout linking to the full block library — but otherwise, if there is an installed result, we shouldn't show suggestions.

Edit: Updated the flow chart in Whimsical to account for this

**Comment by melchoyce** [comment]
Copied the latest version over:

![image](https://user-images.githubusercontent.com/2846578/58353433-7f46e180-7e3c-11e9-8003-65f2b438e9d4.png)

**Comment by mapk** [comment]
Just noting that these will likely change again depending on which route is chosen for Previewing and Installing blocks. The [installing blocks flow](https://github.com/WordPress/block-directory/issues/7) seems like it might change significantly.
