### ISSUE TITLE
Competitive analysis

### ISSUE THREAD

**Issue by melchoyce** [WordPress/block-library#4]
We'll use this to compile research and screenshots.

**Comment by itsjusteileen** [comment]
Screenshots of the UI from block plugin [Ghost Kit](https://wordpress.org/plugins/ghostkit/). The plugin has several patterns that lend themselves to editor-side block selection, and potentially, installation.

Using the Inspector Controls area, the user is presented with three panels.
![screenshot-membersrocket com-2019 04 27-16-01-45](https://user-images.githubusercontent.com/6146600/57024292-38c9e280-6c02-11e9-8037-f2c39a3ee608.png)

The Template panel allows the user to select  a template type from a drop down. Those templates are complete page setups or grouped blocks that can be added to the page.
![screenshot-membersrocket com-2019 04 27-16-17-13](https://user-images.githubusercontent.com/6146600/57024396-7890ca00-6c02-11e9-8322-f67276af6b06.png)

**Comment by karmatosed** [comment]
Is there a list of products you'd like to view for competitive analysis? It might be good to ask in next week's design meeting for people to either pick one from the list to screenshot. Similarly, it might be good to ask if anyone has any to add to mix.

**Comment by melchoyce** [comment]
Good question, and the answer is, I'm not sure. I think finding some good examples of in-app purchases, especially apps that let you preview the feature you're purchasing ahead of time, would be good inspiration. Pretty much any freemium product that lets you preview before purchasing could work.

**Comment by mathetos** [comment]
Similarly, the ["Gutenberg Blocks Template"](https://wordpress.org/plugins/design/) plugin initially comes with ZERO block, but once you open their Gutenberg sidebar panel, you can import the "designs" -- which are essentially sections of Core blocks styled with custom classes and a CSS template. 

![image](https://user-images.githubusercontent.com/930724/57421395-727d8900-71c0-11e9-943c-7c643a50b9cf.png)

So, in terms of existing UI of Gutenberg there seems to be two obvious places where new block discovery/installation can happen:

## Sidebar Panel
Like the Ghost and Block Templates plugins above, adding a custom sidebar to allow for block discovery/installation seems consistent with existing Gutenberg patterns.

PROS:
* hidden unless clicked on
* Lots of vertical space for controls
* Consistent with existing Gutenberg UX

CONS:
* narrow horizontal space
* being hidden means it might not be found
* similar space problems users experience currently with the Customizer, particularly when choosing themes in the Customizer

## Modal Popup
The space problems with a sidebar panel can be overcome with a modal popup. 

PROS: 
* Breaking out of the editing experience provides a visual cue that the actions being taken are different from editing/content creation. Good separation of concerns.
* A modal can have more horizontal space for more flexible layout of the search and block choice options. 

CONS: 
* How will the modal be triggered? It might be very difficult to discover
* It's a new UX for users, that might be jarring

## Summary
Overall, I'm not convinced that block discovery/installation should be happening in the editor at all. So, just voicing those concerns ([like I have already a few times on make.wordpress](https://make.wordpress.org/design/2019/04/26/block-library-installing-blocks-from-within-gutenberg/#comment-25788)). 

But if it's happening no matter what, I wanted to provide constructive feedback as early in the process as possible. Thanks for your leadership and initiative on this @melchoyce and @karmatosed !

**Comment by melchoyce** [comment]
Jetpack has recently been looking at how to handle blocks only available in paid plans, and I think there  are some ideas we could potentially adapt:

![0 1 message-in-editor](https://user-images.githubusercontent.com/2846578/57634509-710ee080-7573-11e9-99b1-4971f2909304.png)
![0 2 message-in-editor](https://user-images.githubusercontent.com/2846578/57634517-7409d100-7573-11e9-8e98-7e15cea749c4.png)

These two ideas in particular fit well into existing Gutenberg patterns:

<img width="755" alt="screenshot-2019-05-10-at-13 48 31-1" src="https://user-images.githubusercontent.com/2846578/57634523-78ce8500-7573-11e9-9d8c-3b33c107b443.png">
<img width="676" alt="upgrade-block" src="https://user-images.githubusercontent.com/2846578/57634527-79ffb200-7573-11e9-97f8-2d3088e6c622.png">

I can easily imagine something like...

 "This is a preview of the (Name) Block. Install to use it on your site. [ INSTALL ]

**Comment by melchoyce** [comment]
A couple "Freemium" / preview examples:

![best_2423](https://user-images.githubusercontent.com/2846578/57656261-e85d6800-75a5-11e9-96d6-41ab7e6d5db9.jpg)
![best_Screen_Shot_2016-07-29_at_13 45 09](https://user-images.githubusercontent.com/2846578/57656262-e8f5fe80-75a5-11e9-8392-45dce49b9314.jpg)
![IMG_3844](https://user-images.githubusercontent.com/2846578/57656266-ee534900-75a5-11e9-9bee-3c6bf40bbd44.PNG)
![IMG_3846](https://user-images.githubusercontent.com/2846578/57656267-eeebdf80-75a5-11e9-97d6-88a0d41d345e.PNG)

https://www.uisources.com/app/pacemaker
https://mobile-patterns.com/search/patterns?q=preview:tag

**Comment by melchoyce** [comment]
Search → Take action from results example:

![image](https://user-images.githubusercontent.com/2846578/57732249-ad713800-766a-11e9-9765-c3a2bb05428c.png)

https://www.pttrns.com/applications/584

**Comment by melchoyce** [comment]
Search results, with people you follow and people you don't follow:

https://mobile-patterns.com/iphone/snapchat/misc-gesture-transition-730

**Comment by melchoyce** [comment]
More search results that mix stuff you have/stuff you don't have: 

https://mobile-patterns.com/iphone/vine/engagement-and-retention-microinteraction-search-438

**Comment by melchoyce** [comment]
Preview modal for in-app purchase:

https://mobile-patterns.com/iphone/path/actions-in-app-purchases-customization-428
https://mobile-patterns.com/iphone/path/actions-in-app-purchases-messaging-143
(WARNING: NSFW language) https://www.uisources.com/explainer/pacemaker-add-filter-to-mix

**Comment by karmatosed** [comment]
Some 'wide' examples of searching and suggestions:

Bear:
![2019-05-16 at 18 38](https://user-images.githubusercontent.com/253067/57875147-19d66d80-780a-11e9-9170-786bc83b2d27.png)

![image](https://user-images.githubusercontent.com/253067/57877115-ec3ff300-780e-11e9-8950-98612bb1be06.png)


Apple:
![image](https://user-images.githubusercontent.com/253067/57876167-99653c00-780c-11e9-9238-10c17ab48fb5.png)

Monzo:
![image](https://user-images.githubusercontent.com/253067/57876186-a6822b00-780c-11e9-8d98-8611619d8bf1.png)

WordPress mobile app:
![image](https://user-images.githubusercontent.com/253067/57876201-b3068380-780c-11e9-8049-9e1e6b0ecb54.png)

Monday:
![image](https://user-images.githubusercontent.com/253067/57876282-e5b07c00-780c-11e9-9bf5-6df5a5cf991b.png)

![image](https://user-images.githubusercontent.com/253067/57876332-fc56d300-780c-11e9-8e58-6c8de466acdd.png)

Searching animation: this moves around showing sections
![image](https://user-images.githubusercontent.com/253067/57876312-f3fe9800-780c-11e9-8f85-8fda1c07021e.png)

Medium:
![image](https://user-images.githubusercontent.com/253067/57876440-37590680-780d-11e9-8a80-2b1112355945.png)

![image](https://user-images.githubusercontent.com/253067/57876672-d8e05800-780d-11e9-9f11-5542dbb0e85b.png)

Reddit:
![image](https://user-images.githubusercontent.com/253067/57876636-bbab8980-780d-11e9-816b-d5019699e321.png)

![image](https://user-images.githubusercontent.com/253067/57876641-c403c480-780d-11e9-9875-4bbaa1f4f608.png)

Twitter:
![image](https://user-images.githubusercontent.com/253067/57876657-cebe5980-780d-11e9-96d4-d07fd95a21ba.png)

Pocket:
![image](https://user-images.githubusercontent.com/253067/57876696-e39aed00-780d-11e9-9d7f-821573c5acfb.png)

![image](https://user-images.githubusercontent.com/253067/57876707-e990ce00-780d-11e9-975b-88c03796f366.png)

**Thoughts:**

- There are some interesting spaces to explore in discovery such as for content in Pocket or Medium.
- Searching for contacts/friends is also a really interesting space to find patterns
- How can delight like Monday's animation or the reddit empty state be added?

**Comment by melchoyce** [comment]
Wrote up a post summarizing these: https://make.wordpress.org/design/2019/05/17/block-library-competitive-analysis-recap/

Closing to mark as complete, but feel free to add more examples here or to that p2 post.
